version: '3'

services:
###> doctrine/doctrine-bundle ###
  
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
  mercure:
    ports:
      - "8001:80"
###< symfony/mercure-bundle ###
